Add 'greater than/less than or equal to' recognizer operators
zowe/zlux-platform pull request #71
Opened 2021-02-08 17:34 UTC by timgerstel

This pull request implements the following features:
- Add 'greater than/less than or equal to' recognizer operators
- Update unit test

Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>

2021-02-08 19:50 UTC, 1000TurquoisePogs approved these changes

2021-02-09 00:33 UTC, DivergentEuropeans commented on base/src/dispatcher/recognizer.spec.ts
> +    it(`should return true for less than (type=string)`, () => {
test says it's checking for less than but we check LTE here

2021-02-09 04:04 UTC, lchudinov commented
Usually, programming languages use 2 letter shorthands for relational operators:
- EQ Equal
- NE Not equal
- LE Less than or equal
- LT Less than
- GE Greater than or equal
- GT Greater than

I think we should follow the same convention.

2021-02-10 04:37 UTC, lchudinov requested changes
Please finish with renaming to make our tests pass.

2021-02-10 04:37 UTC, lchudinov commented on base/src/dispatcher/dispatcher.ts
> +          case 'LTE':
`LE`

2021-02-10 04:37 UTC, lchudinov commented on base/src/dispatcher/dispatcher.ts
> +          case 'GTE':
`GE`

2021-02-10 16:23 UTC, lchudinov approved these changes
Looks good to me now.

2021-02-10 16:23 UTC, merged